[tool.uv.workspace]
members = [
  "source/isaaclab_extension"
]

[tool.uv]
required-environments = [
  "sys_platform == 'linux' and platform_machine == 'x86_64'"
]
exclude-dependencies = ["pywin32"]

[tool.uv.extra-build-dependencies]
isaacsim-kernel = ["wheel-stub"]
flatdict = ["setuptools<82", "wheel"]
